### PR TITLE
Fix author margin & content title size

### LINKED ISSUE #213: Content title too large on content page
image

See figma on left, app on right

### LINKED ISSUE #236: Distance between title and author too large for unregistered content in content lists
## Description

For unregistered content in content lists (like the Drafts page), the vertical distance between the title, author and description are too large.

Unregistered (incorrect):
image

Registered (correct):
image

## To Reproduce

1. Create content with description and save as draft
2. Open Drafts page -> see that vertical space is too large surrounding author

## System

- OS (incl. version): Windows 10
- Hypergraph Desktop version: 0.6.0

## Additional context

Likely introduced by #215

### PR DESCRIPTION
**Pull request by jameslibscie**
- `Heading1` in `typography.js` updated to match design system
- `StyledHeading1` in `content.js` overrides font size from design system (it's sized like an `h2` on the content page, but the title should be an `h1` imo)
- Vertical margin around `AuthorWithoutRegistration` removed.

Closes #213. Closes #236.

image
image

### CODE REVIEW

File: app/components/content/content.js [hunk 1]
```diff
@@ -69,6 +69,7 @@ const Actions = styled.div`
   margin-top: 2rem;
 `
 const StyledHeading1 = styled(Heading1)`
+  font-size: 2rem;
```
Comment (juliangruber) [inline app/components/content/content.js:72]: if you check https://www.figma.com/file/FM8tovSvzNVCKqqOKdseaq/%23169---View-parents-context-for-a-content-module-(mini-mapping)?node-id=76%3A45, the content title size is supposed to be 3rem

File: app/components/content/row.js [hunk 2]
```diff
@@ -72,7 +72,7 @@ const Title = styled.div`
 `
 const AuthorWithoutContentRegistration = styled.span`
   color: ${gray};
-  margin: 1rem 0;
+  margin: 0;
```
Comment (juliangruber) [inline app/components/content/row.js:75]: :+1:

**Review by juliangruber — CHANGES_REQUESTED** [review]

**Review by juliangruber — APPROVED** [review]
